server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: purchase-ws
          uri: lb://purchase-ws
          predicates:
            - Path=/purchase/**
#        - id: users-ws
#          uri: lb://users-ws
#          predicates:
#            - Path=/users/**