#config-server:
#  hostname: localhost
#  port: 8081
#
#spring:
#  cloud:
#    config:
#      username: root
#      password: s3cr3t
#  application:
#    name: purchase-ws
#  config:
#    name: purchase-ws
#    import: optional:configserver:http://localhost:8081

  # ===============================
  # CONFIG LOCAL
  # ===============================



server:
  port: ${PORT:51}

database:
  hostname: localhost
  name: mydatabase
  port: 3306

config-server:
  hostname: localhost
  port: 8081

spring:
  # ===============================
  # JPA / HIBERNATE
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: users-ws

  # ===============================
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.hostname}:${database.port}/${database.name}?autoReconnect=true&serverTimezone=America/Bogota&nullCatalogMeansCurrent=true
    username: myuser
    password: mypass

registry-service:
  hostname: localhost
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://${registry-service.hostname}:${registry-service.port}/eureka