server:
  port: ${PORT:52}

database:
  hostname: db-salesmachines-pod2.cnpcwekdzt0w.us-east-1.rds.amazonaws.com
  name: db-salesmachines-pod2
  port: 3306

spring:
  profiles:
    active:
      - awss3
    #      - local
    default: awss3
  # ===============================
  # JPA / HIBERNATE
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: sales-ws

  # ===============================
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.hostname}:${database.port}/${database.name}?autoReconnect=true&serverTimezone=America/Bogota&nullCatalogMeansCurrent=true
    username: admin
    password: admin123

registry-service:
  hostname: localhost
  port: 8099

eureka:
  client:
    service-url:
      defaultZone: http://${registry-service.hostname}:${registry-service.port}/eureka
logging:
  level:
    org:
      springframework:
        web: INFO
cloud:
  aws:
    region:
      auto: false
      static: us-east-1
    stack:
      auto: false