spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: >-
      jdbc:mysql://${RDS_HOSTNAME:db-salesmachines-pod2.cnpcwekdzt0w.us-east-1.rds.amazonaws.com}:${RDS_PORT:3306}/${RDS_DB_NAME:db-salesmachines-pod2}?enabledTLSProtocols
    username: '${RDS_USERNAME:admin}'
    password: '${RDS_PASSWORD:admin123}'
  security:
    user:
      name: username
      password: password
logging:
  level:
    org:
      springframework:
        web: INFO
cloud:
  aws:
    region:
      auto: false
      static: us-east-1
    stack:
      auto: false