
spring:
  cloud:
    config:
      username: root
      password: s3cr3t
  application:
    name: gateway-service
  config:
    name: gateway-service
    import: optional:configserver:http://localhost:8081
