server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
#      label: develop
      server:
        git:
          uri: https://github.corp.globant.com/tp-COPE/tpam-petspa-podc-api.git
          default-label: develop
          search-paths: config-data
          skip-ssl-validation: true
          username: joseph.rodriguez
          password: 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

  security:
    user:
      name: root
      password: s3cr3t

